exclude_paths:
  - 'acf-json/**'
  - 'vendor/**'
  - 'benchmarks/**/*'
  - 'frontend/node_modules/**'
  - 'frontend/dist/**'
  - 'frontend/static/**'
  - 'frontend/.cache/**'
  - '*.yml'
  - '*.md'
  - '*.sassrc'
  - '*.json'
  - '*.sh'
  - '*.gitignore'
  - '*.json'
  - '*.lock'
  - '*.txt'
  - '*.xml'
  - '*.css'
  - '*.editorconfig'
engines:
  eslint:
    enabled: true
    base_sub_dir: wp-content/themes/lean-theme/frontend
  scsslint:
    enabled: true
    base_sub_dir: wp-content/themes/lean-theme/frontend
  phpcodesniffer:
    enabled: true
    base_sub_dir: wp-content/themes/lean-theme